AllCops:
  DisplayCopNames: true
  Include:
  - "./**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - Gemfile
  - Guardfile
  - Rakefile
  - pkg/**/*
  - spec/fixtures/**/*
  - vendor/**/*

Metrics/LineLength:
  Max: 200
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyElse:
  EnforcedStyle: empty
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  EnforcedStyle: template
Style/Lambda:
  EnforcedStyle: literal
Style/CollectionMethods:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MixinUsage:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/SymbolArray:
  EnforcedStyle: brackets
Style/SpecialGlobalVars:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/StringMethods:
  Enabled: true
Layout/EndOfLine:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/SymbolProc:
  Enabled: false