---
name: PE Support Script Unit Tests
on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          # Use the Ruby version shipped with the oldest supported PE release
          # series.
          #
          # Currently: PE 2018.1 / Ruby 2.4
          ruby-version: '2.4.x'
      - name: Provision Test Tools
        env:
          GEM_SOURCE: 'https://rubygems.org'
          GEM_SKIP_INTERNAL: yes
        run: |
          gem install bundler
          bundle config set path '.bundle/lib'
          bundle install --without=acceptance
      - name: Ruby Unit Tests
        env:
          GEM_SKIP_INTERNAL: yes
        run: |
          bundle exec rake spec
      - name: Bash Unit Tests
        run: |
          shellcheck lib/puppet_x/puppetlabs/support_script/v1/puppet-enterprise-support.sh
